version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs:alpine
    container_name: rfmt-demo-app
    restart: always
    ports:
      - "8081:8081"
    networks:
      - rfmt-demo-network
    command: yarn start

  db:
    image: mongo:latest
    container_name: rfmt-demo-db
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - rfmt-demo-network

networks:
  rfmt-demo-network:
    driver: bridge